using System.Collections.Generic;

namespace HashPDF.WinForms.Localization
{
    public static class TextCatalog
    {
        private static readonly IDictionary<string, string> Greek = new Dictionary<string, string>
        {
            { "HeaderTitle", "HashPDF" },
            { "HeaderSubtitle", "Δημιούργησε SHA-512 hash από οποιοδήποτε αρχείο και παρήγαγε PDF στον ίδιο φάκελο." },
            { "InputTitle", "Επιλογή αρχείου" },
            { "InputSubtitle", "Σύρε ένα αρχείο στο πλαίσιο ή κάνε κλικ στο πλαίσιο για να δημιουργηθεί το PDF hash." },
            { "ThemeLabel", "Θέμα" },
            { "ThemeLight", "Ανοιχτό" },
            { "ThemeDark", "Σκούρο" },
            { "LanguageLabel", "Γλώσσα" },
            { "LanguageGreek", "Ελληνικά" },
            { "LanguageEnglish", "Αγγλικά" },
            { "DropTitle", "Σύρε ή κάνε κλικ εδώ" },
            { "DropHint", "Άφησε ένα μόνο αρχείο ή πάτησε στο πλαίσιο για επιλογή και δημιουργία του συνοδευτικού PDF." },
            { "LoadedFileDropTitle", "Φορτωμένο αρχείο" },
            { "LoadedFileBusyDropTitle", "Φορτώνεται αρχείο" },
            { "LoadedFileDropHint", "{0}\r\n{1}" },
            { "BrowseButton", "Επιλογή αρχείου" },
            { "ResultTitle", "Αποτέλεσμα hash" },
            { "HashCaption", "SHA-512 hash" },
            { "HashPlaceholder", "Το SHA-512 hash θα εμφανιστεί εδώ μετά την επεξεργασία." },
            { "BusyHashPlaceholder", "Γίνεται επεξεργασία του αρχείου και παραγωγή του PDF..." },
            { "FileCaption", "Αρχικό αρχείο" },
            { "PdfCaption", "Παραγόμενο PDF" },
            { "FilePlaceholder", "Δεν έχει επιλεγεί ακόμη." },
            { "PdfPlaceholder", "Δεν έχει παραχθεί ακόμη." },
            { "FileLabel", "Αρχείο:" },
            { "PdfLabel", "PDF:" },
            { "UnavailableValue", "Μη διαθέσιμο" },
            { "BusyPdfValue", "Παράγεται..." },
            { "OpenFolderButton", "Άνοιγμα Φακέλου" },
            { "OpenPdfButton", "Άνοιγμα PDF" },
            { "IdleStatus", "Έτοιμο για νέο αρχείο." },
            { "BusyStatus", "Υπολογίζεται το hash και δημιουργείται το PDF..." },
            { "ReadyStatus", "Το hash και το PDF δημιουργήθηκαν επιτυχώς." },
            { "FailedStatus", "Η δημιουργία του hash ή του PDF απέτυχε." },
            { "ErrorTitle", "Σφάλμα" },
            { "BusyError", "Η εφαρμογή επεξεργάζεται ήδη άλλο αρχείο." },
            { "MissingFileError", "Το επιλεγμένο αρχείο δεν βρέθηκε." },
            { "MissingDirectoryError", "Δεν ήταν δυνατός ο εντοπισμός του φακέλου του αρχικού αρχείου." },
            { "WritePdfError", "Δεν ήταν δυνατή η δημιουργία του PDF στον ίδιο φάκελο με το αρχικό αρχείο." },
            { "GenericProcessingError", "Παρουσιάστηκε μη αναμενόμενο σφάλμα κατά την επεξεργασία του αρχείου." },
            { "InfoTitle", "Πληροφορία" },
            { "CancelButton", "Άκυρο" },
            { "CloseButton", "Κλείσιμο" },
            { "DxfToolsTitle", "Εργαλεία DXF Text" },
            { "DxfToolsDescription", "Μετατρέπει MTEXT σε TEXT στο φορτωμένο DXF και δημιουργεί νέο αρχείο." },
            { "DxfConvertKaekButton", "Μετατροπή PST_KAEK" },
            { "DxfConvertAllButton", "Μετατροπή Όλων" },
            { "DxfFileFilter", "Αρχεία DXF (*.dxf)|*.dxf|Όλα τα αρχεία (*.*)|*.*" },
            { "DxfOpenFileTitle", "Επιλογή DXF αρχείου" },
            { "DxfBusyStatus", "Γίνεται μετατροπή των MTEXT σε TEXT..." },
            { "DxfReadyStatus", "Η μετατροπή ολοκληρώθηκε: {0} MTEXT. Νέο αρχείο: {1}" },
            { "DxfFailedStatus", "Η μετατροπή DXF απέτυχε." },
            { "DxfNoMatchesStatus", "Δεν βρέθηκαν MTEXT για μετατροπή." },
            { "DxfCompleteTitle", "Η μετατροπή ολοκληρώθηκε" },
            { "DxfCompleteMessage", "Δημιουργήθηκε: {0}\r\nMTEXT που μετατράπηκαν: {1}" },
            { "DxfLoadButton", "Φόρτωση αρχείου" },
            { "DxfOpenFolderButton", "Άνοιγμα φακέλου" },
            { "DxfUnsupportedFileError", "Επίλεξε αρχείο DXF με κατάληξη .dxf." },
            { "DxfNoLoadedFileError", "Φόρτωσε πρώτα ένα DXF αρχείο από το πλαίσιο επιλογής." },
            { "DxfBinaryError", "Τα binary DXF δεν υποστηρίζονται ακόμη. Άνοιξε το αρχείο στο CAD πρόγραμμα και αποθήκευσέ το ως ASCII DXF." },
            { "DxfMalformedError", "Το επιλεγμένο DXF δεν έχει έγκυρη ASCII DXF δομή." },
            { "DxfWriteError", "Δεν ήταν δυνατή η δημιουργία του νέου DXF στον ίδιο φάκελο με το αρχικό αρχείο." },
            { "DxfNoMatchesMessage", "Δεν βρέθηκαν MTEXT που να ταιριάζουν με την επιλογή μετατροπής." },
            { "GenericDxfError", "Παρουσιάστηκε μη αναμενόμενο σφάλμα κατά τη μετατροπή του DXF." }
        };

        private static readonly IDictionary<string, string> English = new Dictionary<string, string>
        {
            { "HeaderTitle", "HashPDF" },
            { "HeaderSubtitle", "Create a SHA-512 hash from any file and export a PDF to the same folder." },
            { "InputTitle", "Select a file" },
            { "InputSubtitle", "Drop a file into the panel or click the panel to generate the hash PDF." },
            { "ThemeLabel", "Theme" },
            { "ThemeLight", "Light" },
            { "ThemeDark", "Dark" },
            { "LanguageLabel", "Language" },
            { "LanguageGreek", "Greek" },
            { "LanguageEnglish", "English" },
            { "DropTitle", "Drop or click here" },
            { "DropHint", "Drop a single file or click the panel to choose one and create the companion PDF." },
            { "LoadedFileDropTitle", "Loaded File" },
            { "LoadedFileBusyDropTitle", "Loading File" },
            { "LoadedFileDropHint", "{0}\r\n{1}" },
            { "BrowseButton", "Choose file" },
            { "ResultTitle", "Hash result" },
            { "HashCaption", "SHA-512 hash" },
            { "HashPlaceholder", "The SHA-512 hash will appear here after processing." },
            { "BusyHashPlaceholder", "The file is being processed and the PDF is being created..." },
            { "FileCaption", "Source file" },
            { "PdfCaption", "Generated PDF" },
            { "FilePlaceholder", "Nothing selected yet." },
            { "PdfPlaceholder", "Nothing generated yet." },
            { "FileLabel", "File:" },
            { "PdfLabel", "PDF:" },
            { "UnavailableValue", "Unavailable" },
            { "BusyPdfValue", "Generating..." },
            { "OpenFolderButton", "Open Folder" },
            { "OpenPdfButton", "Open PDF" },
            { "IdleStatus", "Ready for a new file." },
            { "BusyStatus", "Calculating the hash and creating the PDF..." },
            { "ReadyStatus", "The hash and PDF were created successfully." },
            { "FailedStatus", "Hash or PDF generation failed." },
            { "ErrorTitle", "Error" },
            { "BusyError", "The application is already processing another file." },
            { "MissingFileError", "The selected file could not be found." },
            { "MissingDirectoryError", "The source file directory could not be resolved." },
            { "WritePdfError", "The PDF could not be created in the same directory as the source file." },
            { "GenericProcessingError", "An unexpected error occurred while processing the file." },
            { "InfoTitle", "Information" },
            { "CancelButton", "Cancel" },
            { "CloseButton", "Close" },
            { "DxfToolsTitle", "DXF Text Tools" },
            { "DxfToolsDescription", "Converts MTEXT to TEXT in the loaded DXF and creates a new file." },
            { "DxfConvertKaekButton", "Convert PST_KAEK" },
            { "DxfConvertAllButton", "Convert All" },
            { "DxfFileFilter", "DXF files (*.dxf)|*.dxf|All files (*.*)|*.*" },
            { "DxfOpenFileTitle", "Choose DXF file" },
            { "DxfBusyStatus", "Converting MTEXT to TEXT..." },
            { "DxfReadyStatus", "DXF conversion completed: {0} MTEXT item(s). New file: {1}" },
            { "DxfFailedStatus", "DXF conversion failed." },
            { "DxfNoMatchesStatus", "No MTEXT entities were found for conversion." },
            { "DxfCompleteTitle", "Conversion complete" },
            { "DxfCompleteMessage", "Created: {0}\r\nConverted MTEXT entities: {1}" },
            { "DxfLoadButton", "Load file" },
            { "DxfOpenFolderButton", "Open folder" },
            { "DxfUnsupportedFileError", "Choose a DXF file with the .dxf extension." },
            { "DxfNoLoadedFileError", "Load a DXF file from the selection panel first." },
            { "DxfBinaryError", "Binary DXF files are not supported yet. Open the file in your CAD application and save it as ASCII DXF." },
            { "DxfMalformedError", "The selected DXF does not contain a valid ASCII DXF structure." },
            { "DxfWriteError", "The new DXF could not be created in the same directory as the source file." },
            { "DxfNoMatchesMessage", "No MTEXT entities matched the selected conversion scope." },
            { "GenericDxfError", "An unexpected error occurred while converting the DXF." }
        };

        public static string Get(AppLanguage language, string key)
        {
            IDictionary<string, string> source = language == AppLanguage.Greek ? Greek : English;
            if (source.ContainsKey(key))
            {
                return source[key];
            }

            return key;
        }
    }
}
